version: "3"
services:
    node:
        build: .
        ports:
            - 3000:3000
        volumes:
            - ./:/usr/src/app
        depends_on:
            - mysql
    mysql:
        image: mysql:5.7
        environment:
            MYSQL_ROOT_PASSWORD: P@ssw0rd
            MYSQL_DATABASE: PokemonDB
            MYSQL_USER: admin
            MYSQL_PASSWORD: P@ssw0rd
        volumes:
        - mysql-data:/var/lib/mysql 
        ports:
            - 3306:3306                 
volumes:
    mysql-data: {}